name: CFE
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - spotpy
  - tqdm
  - requests
  - netcdf4
  - adjusttext
  - pip:
      - numbakit-ode
      - salib
      - eto